spring.application.name=camel-aula1
camel.main.run-controller=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/cameldb
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always